06-JsfScaffolding/src/main/java/javaone/con3638/jsfscaffolding/entities/Car.java
/*
 * Copyright (C) 2013 Martin Fousek & Mert Caliskan
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package javaone.con3638.jsfscaffolding.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author marfous
 */
@Entity
@Table(name = "CAR")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Car.findAll", query = "SELECT c FROM Car c"),
    @NamedQuery(name = "Car.findById", query = "SELECT c FROM Car c WHERE c.id = :id"),
    @NamedQuery(name = "Car.findByKilometers", query = "SELECT c FROM Car c WHERE c.kilometers = :kilometers"),
    @NamedQuery(name = "Car.findByMark", query = "SELECT c FROM Car c WHERE c.mark = :mark")})
public class Car implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "ID")
    private Long id;
    @Column(name = "KILOMETERS")
    private Integer kilometers;
    @Size(max = 255)
    @Column(name = "MARK")
    private String mark;
    @JoinColumn(name = "OWNER_ID", referencedColumnName = "ID")
    @ManyToOne
    private Owner ownerId;

    public Car() {
    }

    public Car(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getKilometers() {
        return kilometers;
    }

    public void setKilometers(Integer kilometers) {
        this.kilometers = kilometers;
    }

    public String getMark() {
        return mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

    public Owner getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(Owner ownerId) {
        this.ownerId = ownerId;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Car)) {
            return false;
        }
        Car other = (Car) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "javaone.con3638.jsfscaffolding.entities.Car[ id=" + id + " ]";
    }

}

06-JsfScaffolding/src/main/java/javaone/con3638/jsfscaffolding/jsfs/CarController.java
package javaone.con3638.jsfscaffolding.jsfs;

import javaone.con3638.jsfscaffolding.entities.Car;
import javaone.con3638.jsfscaffolding.jsfs.util.JsfUtil;
import javaone.con3638.jsfscaffolding.jsfs.util.PaginationHelper;
import javaone.con3638.jsfscaffolding.sbs.CarFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("carController")
@SessionScoped
public class CarController implements Serializable {

    private Car current;
    private DataModel items = null;
    @EJB
    private javaone.con3638.jsfscaffolding.sbs.CarFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public CarController() {
    }

    public Car getSelected() {
        if (current == null) {
            current = new Car();
            selectedItemIndex = -1;
        }
        return current;
    }

    private CarFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Car) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Car();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/jsf/Bundle").getString("CarCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/jsf/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Car) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/jsf/Bundle").getString("CarUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/jsf/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Car) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/jsf/Bundle").getString("CarDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/jsf/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Car getCar(java.lang.Long id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Car.class)
    public static class CarControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CarController controller = (CarController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "carController");
            return controller.getCar(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Car) {
                Car o = (Car) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Car.class.getName());
            }
        }

    }

}

06-JsfScaffolding/src/main/webapp/car/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateCarTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateCarLabel_id}" for="id" />
                    <h:inputText id="id" value="#{carController.selected.id}" title="#{bundle.CreateCarTitle_id}" required="true" requiredMessage="#{bundle.CreateCarRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateCarLabel_kilometers}" for="kilometers" />
                    <h:inputText id="kilometers" value="#{carController.selected.kilometers}" title="#{bundle.CreateCarTitle_kilometers}" />
                    <h:outputLabel value="#{bundle.CreateCarLabel_mark}" for="mark" />
                    <h:inputText id="mark" value="#{carController.selected.mark}" title="#{bundle.CreateCarTitle_mark}" />
                    <h:outputLabel value="#{bundle.CreateCarLabel_ownerId}" for="ownerId" />
                    <h:selectOneMenu id="ownerId" value="#{carController.selected.ownerId}" title="#{bundle.CreateCarTitle_ownerId}" >
                        <f:selectItems value="#{ownerController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{carController.create}" value="#{bundle.CreateCarSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{carController.prepareList}" value="#{bundle.CreateCarShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateCarIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

06-JsfScaffolding/src/main/webapp/car/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditCarTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditCarLabel_id}" for="id" />
                    <h:inputText id="id" value="#{carController.selected.id}" title="#{bundle.EditCarTitle_id}" required="true" requiredMessage="#{bundle.EditCarRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditCarLabel_kilometers}" for="kilometers" />
                    <h:inputText id="kilometers" value="#{carController.selected.kilometers}" title="#{bundle.EditCarTitle_kilometers}" />
                    <h:outputLabel value="#{bundle.EditCarLabel_mark}" for="mark" />
                    <h:inputText id="mark" value="#{carController.selected.mark}" title="#{bundle.EditCarTitle_mark}" />
                    <h:outputLabel value="#{bundle.EditCarLabel_ownerId}" for="ownerId" />
                    <h:selectOneMenu id="ownerId" value="#{carController.selected.ownerId}" title="#{bundle.EditCarTitle_ownerId}" >
                        <f:selectItems value="#{ownerController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{carController.update}" value="#{bundle.EditCarSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditCarViewLink}"/>
                <br />
                <h:commandLink action="#{carController.prepareList}" value="#{bundle.EditCarShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditCarIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

06-JsfScaffolding/src/main/webapp/car/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListCarTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListCarEmpty}" rendered="#{carController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{carController.items.rowCount > 0}">
                    <h:outputText value="#{carController.pagination.pageFirstItem + 1}..#{carController.pagination.pageLastItem + 1}/#{carController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{carController.previous}" value="#{bundle.Previous} #{carController.pagination.pageSize}" rendered="#{carController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{carController.next}" value="#{bundle.Next} #{carController.pagination.pageSize}" rendered="#{carController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{carController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCarTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCarTitle_kilometers}"/>
                            </f:facet>
                            <h:outputText value="#{item.kilometers}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCarTitle_mark}"/>
                            </f:facet>
                            <h:outputText value="#{item.mark}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCarTitle_ownerId}"/>
                            </f:facet>
                            <h:outputText value="#{item.ownerId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{carController.prepareView}" value="#{bundle.ListCarViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{carController.prepareEdit}" value="#{bundle.ListCarEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{carController.destroy}" value="#{bundle.ListCarDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{carController.prepareCreate}" value="#{bundle.ListCarCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListCarIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

06-JsfScaffolding/src/main/webapp/car/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewCarTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewCarLabel_id}"/>
                    <h:outputText value="#{carController.selected.id}" title="#{bundle.ViewCarTitle_id}"/>
                    <h:outputText value="#{bundle.ViewCarLabel_kilometers}"/>
                    <h:outputText value="#{carController.selected.kilometers}" title="#{bundle.ViewCarTitle_kilometers}"/>
                    <h:outputText value="#{bundle.ViewCarLabel_mark}"/>
                    <h:outputText value="#{carController.selected.mark}" title="#{bundle.ViewCarTitle_mark}"/>
                    <h:outputText value="#{bundle.ViewCarLabel_ownerId}"/>
                    <h:outputText value="#{carController.selected.ownerId}" title="#{bundle.ViewCarTitle_ownerId}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{carController.destroyAndView}" value="#{bundle.ViewCarDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewCarEditLink}"/>
                <br />
                <h:commandLink action="#{carController.prepareCreate}" value="#{bundle.ViewCarCreateLink}" />
                <br />
                <h:commandLink action="#{carController.prepareList}" value="#{bundle.ViewCarShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewCarIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>