03-ExpressionLanguage3/src/main/java/javaone/con3638/expressionlanguage3/CollectionOperationsBean.java
/*
 * Copyright (C) 2013 Martin Fousek & Mert Caliskan
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package javaone.con3638.expressionlanguage3;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 * Bean used for showing collection operations feature.
 *
 * @author Martin Fousek <marfous@netbeans.org>
 */
@Named("cob")
@RequestScoped
public class CollectionOperationsBean {

    public boolean isString(Object o) {
        return o instanceof String;
    }

    public boolean isInteger(Object o) {
        return o instanceof Integer;
    }

    public void logToConsole(Object o) {
        Logger.getGlobal().log(Level.INFO, "Logging value from the EL: {0}", o);
    }
}

03-ExpressionLanguage3/src/main/java/javaone/con3638/expressionlanguage3/ElProcessorBean.java
/*
 * Copyright (C) 2013 Martin Fousek & Mert Caliskan
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package javaone.con3638.expressionlanguage3;

import javax.el.ELProcessor;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 * Usage of standalone EL 3.0 ElProcessor.
 *
 * @author Martin Fousek <marfous@netbeans.org>
 */
@Named
@RequestScoped
public class ElProcessorBean {

    private static final ELProcessor EL_PROCESSOR = new ELProcessor();

    private static final String HELLO_WORLD = "'Hello' += 'World' += '!'";
    private static final String MATH_OPERATION = "5 * 8 % 6";
    private static final String MORE_EVALUATIONS = "a = 50; b = 51; a + b";

    public String getStringKey() {
        return HELLO_WORLD;
    }

    public Object getStringValue() {
        return EL_PROCESSOR.eval(HELLO_WORLD);
    }

    public String getMathExpressionKey() {
        return MATH_OPERATION;
    }

    public Object getMathExpressionValue() {
        return EL_PROCESSOR.eval(MATH_OPERATION);
    }

    public String getMoreEvaluationsKey() {
        return MORE_EVALUATIONS;
    }

    public Object getMoreEvaluationsValue() {
        return EL_PROCESSOR.eval(MORE_EVALUATIONS);
    }

    // Workaround for the issue https://java.net/jira/browse/EL_SPEC-16 in the
    //  usage of static fields and methods within Facelet
    public Object getEvaluatedValue(String expression) {
        return EL_PROCESSOR.eval(expression);
    }

}

03-ExpressionLanguage3/src/main/java/javaone/con3638/expressionlanguage3/OperatorsBean.java
/*
 * Copyright (C) 2013 Martin Fousek & Mert Caliskan
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package javaone.con3638.expressionlanguage3;

import java.util.Arrays;
import java.util.List;
import javax.inject.Named;

/**
 * Bean used for showing EL 3.0 assignment operator feature.
 *
 * @author Martin Fousek <marfous@netbeans.org>
 */
@Named
@javax.enterprise.context.RequestScoped
public class OperatorsBean {

    public List<String> getCarBrands() {
        return Arrays.asList("Škoda", "BMW", "Ford", "Toyota", "Mazda", "Mercedes");
    }

}

03-ExpressionLanguage3/src/main/webapp/collectionOperations.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    Collection operations can be used over collections and arrays. It's feature aligned with Stream API (Java SE 8) but it can be used even with Java SE 7.<br/>
    <p:panelGrid>
        <f:facet name="header">
            <p:row>
                <p:column>Operation</p:column>
                <p:column>Return Type</p:column>
                <p:column colspan="2">Sample and Resolved Value</p:column>
            </p:row>
        </f:facet>

        <p:row>
            <p:column styleClass="keyText">allMatch()</p:column>
            <p:column styleClass="keyText">boolean</p:column>
            <p:column>
                <code>\#{['pear', 'whatever'].stream().allMatch(i->cob.isString(i))}</code>
            </p:column>
            <p:column>
                #{['pear', 'whatever'].stream().allMatch(i->cob.isString(i))}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">anyMatch()</p:column>
            <p:column styleClass="keyText">boolean</p:column>
            <p:column>
                <code>\#{['pear', 'whatever'].stream().allMatch(i->cob.isInteger(i))}</code>
            </p:column>
            <p:column>
                #{['pear', 'whatever'].stream().allMatch(i->cob.isInteger(i))}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">average()</p:column>
            <p:column styleClass="keyText">Optional</p:column>
            <p:column>
                <code>\#{[1, 2, 3].stream().average().get()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3].stream().average().get()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">count()</p:column>
            <p:column styleClass="keyText">Object</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 6].stream().count()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 6].stream().count()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">distinct()</p:column>
            <p:column styleClass="keyText">Stream</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 3].stream().distinct().toList()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 3].stream().distinct().toList()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">filter()</p:column>
            <p:column styleClass="keyText">Stream</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 3].stream().filter(i->i lt 3).toList()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 3].stream().filter(i->i lt 3).toList()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">findFirst()</p:column>
            <p:column styleClass="keyText">Optional</p:column>
            <p:column>
                <code>\#{['pear', 'whatever'].stream().findFirst().get()}</code>
            </p:column>
            <p:column>
                #{['pear', 'whatever'].stream().findFirst().get()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">flatMap()</p:column>
            <p:column styleClass="keyText">Stream</p:column>
            <p:column>
                <code>\#{[{1, 2},{3, 3}].stream().flatMap(i->i.stream()).toList()}</code>
            </p:column>
            <p:column>
                <h:outputText value="#{[{1, 2},{3, 3}].stream().flatMap(i->i.stream()).toList()}"/>
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">forEach()</p:column>
            <p:column styleClass="keyText">void</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 3].stream().forEach(i->i * 3)}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 3].stream().forEach(i->cob.logToConsole(i))}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">limit()</p:column>
            <p:column styleClass="keyText">Stream</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 3].stream().limit(2).toList()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 3].stream().limit(2).toList()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">map()</p:column>
            <p:column styleClass="keyText">Stream</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 3].stream().map(i-> i + 4).toList()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 3].stream().map(i-> i + 4).toList()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">max()</p:column>
            <p:column styleClass="keyText">Optional</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 8].stream().max().get()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 8].stream().max().get()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">min()</p:column>
            <p:column styleClass="keyText">Optional</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 8].stream().min().get()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 8].stream().min().get()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">noneMatch()</p:column>
            <p:column styleClass="keyText">boolean</p:column>
            <p:column>
                <code>\#{['word', null, 4, 'cent'].stream().noneMatch(i->i eq null)}</code>
            </p:column>
            <p:column>
                #{['word', null, 4, 'cent'].stream().noneMatch(i->i eq null)}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">peek()</p:column>
            <p:column styleClass="keyText">Stream</p:column>
            <p:column>
                <code>\#{['word', null, 4, 'cent'].stream().peek(i->cob.logToConsole(i)).toList()}</code>
            </p:column>
            <p:column>
                #{['word', null, 4, 'cent'].stream().peek(i->cob.logToConsole(i)).toList()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">reduce()</p:column>
            <p:column styleClass="keyText">Optional</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 8].stream().reduce((i,j)->(i > j ? i : j)).get()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 8].stream().reduce((i,j)->(i > j ? i : j)).get()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">sorted()</p:column>
            <p:column styleClass="keyText">Stream</p:column>
            <p:column>
                <code>\#{['a', 'z', 'g'].stream().sorted().toList()}</code>
            </p:column>
            <p:column>
                #{['a', 'z', 'g'].stream().sorted().toList()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">substream()</p:column>
            <p:column styleClass="keyText">Stream</p:column>
            <p:column>
                <code>\#{['a', 'z', 'g'].stream().substream(1).toList()}</code>
            </p:column>
            <p:column>
                #{['a', 'z', 'g'].stream().substream(1).toList()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">sum()</p:column>
            <p:column styleClass="keyText">Object</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 3].stream().sum()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 3].stream().sum()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">toArray()</p:column>
            <p:column styleClass="keyText">Object[]</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 3].stream().toArray()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 3].stream().toArray()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">toList()</p:column>
            <p:column styleClass="keyText">Object</p:column>
            <p:column>
                <code>\#{[1, 2, 3, 3].stream().toList()}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3, 3].stream().toList()}
            </p:column>
        </p:row>

    </p:panelGrid>
</ui:composition>

03-ExpressionLanguage3/src/main/webapp/collections.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    Construction of collections dynamically at time of the artifact processing. Values of collections can be of mixed types.<br/>
    <p:panelGrid>
        <f:facet name="header">
            <p:row>
                <p:column>Collection Type</p:column>
                <p:column colspan="2">Syntax and Resolved Element</p:column>
            </p:row>
        </f:facet>

        <p:row>
            <p:column rowspan="2" styleClass="keyText">Lists</p:column>
            <p:column>
                integer values: <code>\#{[1, 2, 3]}</code>
            </p:column>
            <p:column>
                #{[1, 2, 3]}
            </p:column>
        </p:row>
        <p:row>
            <p:column>
                mixed values: <code>\#{[Boolean(true), "Hello", 5]}</code>
            </p:column>
            <p:column>
                #{[Boolean(true), "Hello", 5]}
            </p:column>
        </p:row>

        <p:row>
            <p:column rowspan="2" styleClass="keyText">Sets</p:column>
            <p:column>
                integer values: <code>\#{{1, 2, 3}}</code>
            </p:column>
            <p:column>
                <!-- Why using outputText? See https://java.net/jira/browse/JAVASERVERFACES-2891-->
                <h:outputText value="#{{1, 2, 3}}" />
            </p:column>
        </p:row>
        <p:row>
            <p:column>
                mixed values: <code>\#{{'one', 2, Integer(3)}}</code>
            </p:column>
            <p:column>
                <h:outputText value="#{{'one', 2, Integer(3)}}" />
            </p:column>
        </p:row>

        <p:row>
            <p:column rowspan="3" styleClass="keyText">Maps</p:column>
            <p:column>
                integer key, mixed value: <code>\#{{1:'one', 2:2, 3:null}}</code>
            </p:column>
            <p:column>
                <!-- Why using outputText? See https://java.net/jira/browse/JAVASERVERFACES-2891-->
                <h:outputText value="#{{1:'one', 2:2, 3:null}}" />
            </p:column>
        </p:row>
        <p:row>
            <p:column>
                string key, mixed value: <code>\#{{'one':1, 'two':2, 'three':3}}</code>
            </p:column>
            <p:column>
                <h:outputText value="#{{'one':1, 'two':2, 'three':3}}" />
            </p:column>
        </p:row>
        <p:row>
            <p:column>
                nested values: <code>\#{{1:['array'], 2:{'set'}, 3:{'id' : 'map'}}}</code>
            </p:column>
            <p:column>
                <h:outputText value="#{{1:['array'], 2:{'set'}, 3:{'id' : 'map'}}}" />
            </p:column>
        </p:row>

    </p:panelGrid>
</ui:composition>

03-ExpressionLanguage3/src/main/webapp/elprocessor.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    Used standalone ELProcessor API for evaluation of the EL expressions.<br/>
    Java source: <code>new ELProcessor().eval(#{elProcessorBean.stringKey});</code>
    <p:panelGrid>
        <f:facet name="header">
            <p:row>
                <p:column>Parameter to evaluate</p:column>
                <p:column>Evaluated value</p:column>
            </p:row>
        </f:facet>

        <p:row>
            <p:column styleClass="keyText">#{elProcessorBean.stringKey}</p:column>
            <p:column styleClass="valueText">#{elProcessorBean.stringValue}</p:column>
        </p:row>
        <p:row>
            <p:column styleClass="keyText">#{elProcessorBean.mathExpressionKey}</p:column>
            <p:column styleClass="valueText">#{elProcessorBean.mathExpressionValue}</p:column>
        </p:row>
        <p:row>
            <p:column styleClass="keyText">#{elProcessorBean.moreEvaluationsKey}</p:column>
            <p:column styleClass="valueText">#{elProcessorBean.moreEvaluationsValue}</p:column>
        </p:row>

    </p:panelGrid>
</ui:composition>

03-ExpressionLanguage3/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Expression Language 3.0</title>
    </h:head>
    <h:body>
        <h1>Expression Language 3.0</h1>
        <p:tabView effect="fade" effectDuration="fast">
            <p:tab title="Standalone ELProcessor">
                <h:panelGrid columns="1" cellpadding="10">
                    <ui:include src="elprocessor.xhtml"/>
                </h:panelGrid>
            </p:tab>
            <p:tab title="Operators">
                <h:panelGrid columns="1" cellpadding="10">
                    <ui:include src="operators.xhtml"/>
                </h:panelGrid>
            </p:tab>
            <p:tab title="Static Fields and Methods">
                <h:panelGrid columns="1" cellpadding="10">
                    <ui:include src="staticfields.xhtml"/>
                </h:panelGrid>
            </p:tab>
            <p:tab title="Collections">
                <h:panelGrid columns="1" cellpadding="10">
                    <ui:include src="collections.xhtml"/>
                </h:panelGrid>
            </p:tab>
            <p:tab title="Lambda Expressions">
                <h:panelGrid columns="1" cellpadding="10">
                    <ui:include src="lambdas.xhtml"/>
                </h:panelGrid>
            </p:tab>
            <p:tab title="Collection Operations">
                <h:panelGrid columns="1" cellpadding="10">
                    <ui:include src="collectionOperations.xhtml"/>
                </h:panelGrid>
            </p:tab>
        </p:tabView>  
    </h:body>
</html>

03-ExpressionLanguage3/src/main/webapp/lambdas.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    Lambda expressions are similar to the Java SE 8 ones. It can be immediately resolved, referenced, passed as a method parameter.<br/>
    <p:panelGrid>
        <f:facet name="header">
            <p:row>
                <p:column>Description</p:column>
                <p:column colspan="2">Sample and Resolved Value</p:column>
            </p:row>
        </f:facet>

        <p:row>
            <p:column styleClass="keyText">No parameter lambda</p:column>
            <p:column>
                <code>\#{v = 5} * 2 = \#{(()->2 * v)()}</code>
            </p:column>
            <p:column>
                #{v = 5} * 2 = #{(()->2 * v)()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">One parameter lambda</p:column>
            <p:column>
                <code>\#{(i->2 * i)(2)}</code>
            </p:column>
            <p:column>
                #{(i->2 * i)(2)}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">More parameter lambda</p:column>
            <p:column>
                <code>\#{((i, j, k)->1 * i + 2 * j + 3 * k)(1, 2, 3)}</code>
            </p:column>
            <p:column>
                #{((i, j, k)->1 * i + 2 * j + 3 * k)(1, 2, 3)}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">Referenced lambda</p:column>
            <p:column>
                <code>\#{divLambda = (a, b)->a div b; divLambda(20, 3)}</code>
            </p:column>
            <p:column>
                #{divLambda = (a, b)->a div b; divLambda(20, 3)}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">Lambda as method argument</p:column>
            <p:column colspan="2">
                See later...
            </p:column>
        </p:row>
    </p:panelGrid>
</ui:composition>

03-ExpressionLanguage3/src/main/webapp/operators.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    New operators defined by Expression Language 3.0 specification.<br/>
    <p:panelGrid>
        <f:facet name="header">
            <p:row>
                <p:column>Operator Type</p:column>
                <p:column colspan="2">Several examples</p:column>
            </p:row>
        </f:facet>

        <p:row>
            <p:column rowspan="2" styleClass="keyText">String Concatenation Operator <code>+=</code></p:column>
            <p:column>
                <code>\#{'Welcome' += ' ' += 'to' += ' ' += 'JavaOne!'}</code>
            </p:column>
            <p:column>
                #{'Welcome' += ' ' += 'to' += ' ' += 'JavaOne!'}
            </p:column>
        </p:row>
        <p:row>
            <p:column>
                <code>\#{'It\'s not like integer increment: ' += 5 += 6}</code>
            </p:column>
            <p:column>
                #{'It\'s not like integer increment: ' += 5 += 6}
            </p:column>
        </p:row>

        <p:row>
            <p:column rowspan="2" styleClass="keyText">Semicolon Operator <code>;</code></p:column>
            <p:column>
                <code>\#{localVar = 'Hello World!'; localVar}</code>
            </p:column>
            <p:column>
                #{localVar = 'Hello World!'; localVar}
            </p:column>
        </p:row>
        <p:row>
            <p:column>
                <code>\#{5 + 6; ' '; operatorsBean.carBrands[5]}</code>
            </p:column>
            <p:column>
                #{5 + 6; ' '; operatorsBean.carBrands[5]}
            </p:column>
        </p:row>

        <p:row>
            <p:column rowspan="3" styleClass="keyText">Assignment Operator <code>=</code></p:column>
            <p:column>
                <code>\#{a = 1; b = 2; c = a + b}</code>
            </p:column>
            <p:column>
                #{a = 1; b = 2; c = a + b}
            </p:column>
        </p:row>
        <p:row>
            <p:column>
                <code>\#{brands = operatorsBean.carBrands; brands[0]}</code>
            </p:column>
            <p:column>
                #{brands = operatorsBean.carBrands; brands[0]}
            </p:column>
        </p:row>
        <p:row>
            <p:column>
                <code>\#{brand = operatorsBean.carBrands[0];''} \#{brand.toLowerCase()}</code>
            </p:column>
            <p:column>
                #{brand = operatorsBean.carBrands[0];''} #{brand.toLowerCase()}
            </p:column>
        </p:row>

        <p:row>
            <p:column styleClass="keyText">Lambda Operator <code>-></code></p:column>
            <p:column colspan="2" styleClass="valueText">see later...</p:column>
        </p:row>
    </p:panelGrid>
</ui:composition>

03-ExpressionLanguage3/src/main/webapp/staticfields.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    Static fields and methods can be referenced as 'classname.fieldname'. It's restricted only to the static, public
    fields and methods, by default placed only within the <code>java.lang.*</code> package.<br/>
    <p:panelGrid>
        <f:facet name="header">
            <p:row>
                <p:column>Expression</p:column>
                <p:column>Evaluated Value</p:column>
            </p:row>
        </f:facet>

        <p:row>
            <p:column>
                <code>\#{Integer.MAX_VALUE}</code>
            </p:column>
            <p:column>
                <!-- Workaround for the issue https://java.net/jira/browse/EL_SPEC-16 in
                    the usage of static fields and methods within Facelet. -->
                <h:outputText value="#{elProcessorBean.getEvaluatedValue('Integer.MAX_VALUE')}"/>
            </p:column>
        </p:row>
        <p:row>
            <p:column>
                <code>\#{Boolean(true)}</code>
            </p:column>
            <p:column>
                #{Boolean(true)}
            </p:column>
        </p:row>
        <p:row>
            <p:column>
                <code>\#{Integer.toHexString(16)}</code>
            </p:column>
            <p:column>
                <!-- Workaround for the issue https://java.net/jira/browse/EL_SPEC-16 in
                    the usage of static fields and methods within Facelet. -->
                <h:outputText value="#{elProcessorBean.getEvaluatedValue('Integer.toHexString(16)')}"/>
            </p:column>
        </p:row>
    </p:panelGrid>
</ui:composition>